# SPDX-License-Identifier: Apache-2.0
"""Generate the CLI reference section of docs/toolchain.md from the typer app.

The block between ``<!-- cli-ref:start -->`` and ``<!-- cli-ref:end -->`` is
derived: every ``ant`` command and subcommand with its arguments and options,
walked from the live click tree so it cannot drift from the code.

    uv run python tools/gen_cli_reference.py          # rewrite the block in place
    uv run python tools/gen_cli_reference.py --check  # exit 1 if the block is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import click
import typer.main

from ant_rdf.cli import app

DOC = Path(__file__).resolve().parents[1] / "docs" / "toolchain.md"
START, END = "<!-- cli-ref:start -->", "<!-- cli-ref:end -->"


def _walk(cmd: click.Command, path: str):
    if isinstance(cmd, click.Group):
        yield path, cmd, True
        for name in sorted(cmd.commands):
            yield from _walk(cmd.commands[name], f"{path} {name}")
    else:
        yield path, cmd, False


def _params(cmd: click.Command) -> list[str]:
    rows = []
    for p in cmd.params:
        if isinstance(p, click.Argument):
            rows.append(f"- `{p.human_readable_name}`" + (" (required)" if p.required else ""))
        elif isinstance(p, click.Option):
            if p.name == "help":
                continue
            names = ", ".join(f"`{o}`" for o in p.opts + p.secondary_opts)
            help_ = (p.help or "").strip()
            req = " (required)" if p.required else ""
            rows.append(f"- {names}{req}" + (f" — {help_}" if help_ else ""))
    return rows


def render() -> str:
    root = typer.main.get_command(app)
    out: list[str] = [START, "", "_Generated by `tools/gen_cli_reference.py` — do not edit by hand._", ""]
    for path, cmd, is_group in _walk(root, "ant"):
        if path == "ant":
            continue
        out.append(f"### `{path}`")
        out.append("")
        doc = (cmd.help or "").strip()
        if doc:
            out.append(doc.replace("\n\n", "\n").replace("\n", " "))
            out.append("")
        if is_group:
            subs = ", ".join(f"`{path} {n}`" for n in sorted(cmd.commands))
            out.append(f"Subcommands: {subs}")
            out.append("")
            continue
        rows = _params(cmd)
        if rows:
            out.extend(rows)
            out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    text = DOC.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n", re.S)
    if not pattern.search(text):
        print(f"{DOC}: missing {START} / {END} markers", file=sys.stderr)
        return 2
    new = pattern.sub(lambda _m: render(), text)
    if "--check" in argv:
        if new != text:
            print(f"{DOC}: CLI reference block is stale; run tools/gen_cli_reference.py", file=sys.stderr)
            return 1
        print("CLI reference block is up to date")
        return 0
    DOC.write_text(new, encoding="utf-8")
    print(f"wrote CLI reference into {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
