# SPDX-License-Identifier: Apache-2.0
"""ActantProfile compiler — renders one Actant as a Markdown profile.

Shows the actant's role(s) it's been characterized into, who enrols it and
who it enrols, which network(s) it participates in, and what inscriptions
it produces (if any).
"""

from __future__ import annotations

from rdflib import Dataset, URIRef
from rdflib.namespace import RDF

from ant_rdf import ANT
from ant_rdf.compilers._common import (
    description_of,
    label_of,
    local_name,
    md_table,
)


def compile_(ds: Dataset, subject: URIRef | None = None) -> str:
    g = ds.default_graph

    if subject is None:
        candidates = sorted(
            s for s in g.subjects(RDF.type, ANT.Actant) if isinstance(s, URIRef)
        )
        if not candidates:
            raise ValueError("No ant:Actant instances in the loaded graph.")
        subject = candidates[0]

    name = label_of(g, subject)
    desc = description_of(g, subject)

    lines = [
        f"# Actant Profile: {name}",
        "",
        f"<!-- {subject} -->",
        "",
        "## Description",
        "",
        desc or "_(no description)_",
        "",
        "## Networks this actant participates in",
        "",
    ]
    nets = sorted(o for o in g.objects(subject, ANT.participatesIn) if isinstance(o, URIRef))
    if nets:
        for n in nets:
            lines.append(f"- {label_of(g, n)} (`{n}`)")
    else:
        lines.append("_(none recorded)_")
    lines.append("")

    # Characterizations targeting this actant
    chars = sorted(c for c in g.subjects(ANT.characterizes, subject) if isinstance(c, URIRef))
    lines += ["## Characterizations of this actant", ""]
    if chars:
        rows = []
        for c in chars:
            role = next(iter(g.objects(c, ANT.assignsRole)), None)
            net = next(iter(g.objects(c, ANT.withinNetwork)), None)
            prac = next(iter(g.objects(c, ANT.perPractice)), None)
            inv = next(iter(g.objects(c, ANT.invarianceCriterion)), None)
            rows.append([
                local_name(str(role)) if role else "?",
                local_name(str(net)) if net else "?",
                local_name(str(prac)) if prac else "_(unspecified)_",
                str(inv) if inv else "_(unspecified)_",
                description_of(g, c),
            ])
        lines.append(md_table(
            ["Role", "Within network", "Per practice", "Invariance", "Description"], rows,
        ))
    else:
        lines.append("_No characterizations targeting this actant._")
    lines.append("")

    # Who enrols this actant, and who this actant enrols
    enrolled_by = sorted(s for s in g.subjects(ANT.enrols, subject) if isinstance(s, URIRef))
    enrols_others = sorted(o for o in g.objects(subject, ANT.enrols) if isinstance(o, URIRef))
    lines += ["## Enrolment relations", ""]
    if enrolled_by:
        lines.append("**Enrolled by:**")
        for s in enrolled_by:
            lines.append(f"- {label_of(g, s)} (`{s}`)")
        lines.append("")
    if enrols_others:
        lines.append("**Enrols:**")
        for o in enrols_others:
            lines.append(f"- {label_of(g, o)} (`{o}`)")
        lines.append("")
    if not enrolled_by and not enrols_others:
        lines.append("_No ant:enrols relations recorded._")
        lines.append("")

    # Inscriptions produced
    inscr = sorted(o for o in g.objects(subject, ANT.inscribes) if isinstance(o, URIRef))
    if inscr:
        lines += ["## Inscriptions this actant produces", ""]
        for i in inscr:
            lines.append(f"- {label_of(g, i)} (`{i}`)")
        lines.append("")

    # Programs of action
    progs = sorted(o for o in g.objects(subject, ANT.hasProgram) if isinstance(o, URIRef))
    if progs:
        lines += ["## Programs of action", ""]
        for p in progs:
            lines.append(f"- {label_of(g, p)} (`{p}`)")
        lines.append("")

    lines += [
        "---",
        "",
        f"<!-- generated by ant-rdf; see {subject} -->",
    ]
    return "\n".join(lines)
