# SPDX-License-Identifier: Apache-2.0
"""TranslationTrace compiler — renders one Translation as a Markdown trace.

The four Callon moments rendered narratively in canonical order. Each
moment gets its own section with its label, description, and any
participants we can discover via the surrounding graph.
"""

from __future__ import annotations

from rdflib import Dataset, URIRef
from rdflib.namespace import RDF

from ant_rdf import ANT
from ant_rdf.compilers._common import description_of, label_of, local_name

# Canonical moment ordering (per Callon 1986)
_MOMENT_ORDER = [
    "Problematization",
    "Interessement",
    "Enrolment",
    "Mobilization",
]


def compile_(ds: Dataset, subject: URIRef | None = None) -> str:
    g = ds.default_graph

    if subject is None:
        # Find a top-level Translation (one with ant:hasMoment relations)
        candidates = [
            s for s in g.subjects(RDF.type, ANT.Translation)
            if isinstance(s, URIRef) and list(g.objects(s, ANT.hasMoment))
        ]
        if not candidates:
            raise ValueError("No top-level ant:Translation instances in the loaded graph.")
        subject = sorted(candidates)[0]

    name = label_of(g, subject)
    desc = description_of(g, subject)

    lines = [
        f"# Translation Trace: {name}",
        "",
        f"<!-- {subject} -->",
        "",
        "## Description",
        "",
        desc or "_(no description)_",
        "",
        "## Moments (in canonical order)",
        "",
    ]

    # Index moments by their ant: local-name type
    moments = sorted(o for o in g.objects(subject, ANT.hasMoment) if isinstance(o, URIRef))
    by_kind: dict[str, list[URIRef]] = {}
    for m in moments:
        for t in g.objects(m, RDF.type):
            if isinstance(t, URIRef) and str(t).startswith(str(ANT)):
                kind = local_name(str(t))
                if kind != "Translation":
                    by_kind.setdefault(kind, []).append(m)
                    break

    for kind in _MOMENT_ORDER:
        lines.append(f"### {kind}")
        lines.append("")
        items = by_kind.get(kind, [])
        if not items:
            lines.append(f"_(no {kind.lower()} recorded — Tier-2 will warn unless waived)_")
            lines.append("")
            continue
        for m in items:
            lines.append(f"**{label_of(g, m)}**")
            lines.append("")
            lines.append(f"<!-- {m} -->")
            lines.append("")
            lines.append(description_of(g, m) or "_(no description)_")
            lines.append("")

    # Any other moments not in the canonical four kinds
    other = sorted(k for k in by_kind if k not in _MOMENT_ORDER)
    if other:
        lines.append("### Other moments")
        lines.append("")
        for kind in other:
            for m in by_kind[kind]:
                lines.append(f"**{kind}: {label_of(g, m)}**")
                lines.append("")
                lines.append(f"<!-- {m} -->")
                lines.append("")
                lines.append(description_of(g, m) or "_(no description)_")
                lines.append("")

    lines += [
        "---",
        "",
        f"<!-- generated by ant-rdf; see {subject} -->",
    ]
    return "\n".join(lines)
